### ISSUE TITLE
CIEXYZ, CIELAB

### ISSUE THREAD

**Issue by waynewccheng** [plemaillet/read_spectral_data#1]
I don't have a concrete idea, but I guess the user would be interested in seeing something about CIEXYZ/CIELAB data because we always ask our sponsors to provide such data.

It doesn't need to be fancy. We can start from something very simple using text only like a table.

For example, with a location (x,y) and a (pre-stored) light source LS, a class method would display the CIE X, Y, Z, x, y, L*, a*, and b* values. Of course, the reference white information needs to be shown at the same time.

**Comment by plemaillet** [comment]
I added the scatter3 plots for XYZ, LAB and RGB + XYZ0, XZY, LAB and Yxy for a list of pixel position

**Comment by waynewccheng** [comment]
Please check: (1) the xlabel, ylabel, and zlabel are incorrectly labeled, and (2) where the yellow colors come from.

**Comment by plemaillet** [comment]
Yellow pixels: it seems there is an artifact for some pixels in the image. For example at pixel [145 341]. I tried with 2 other images and there was no problem at this specific pixel position so that's not the camera. So there may have been a measurements problem there, maybe dust on the slide or with the 100% transmittance measurements. 

Scatter3 plot: I updated these, I checked the values for a couple of pixels by checking the values for X-Y view and so-on and it seems OK. The datacursor now gives the position of the pixel as a row position in the (sixex * sizey, n) tables (Index tag). There was also a color problem in the plotting of the transmittance (for this one, it's now possible to enter the pixel position or the row position of the (sixex * sizey, n) tables).

I uploaded the Uterine Cervix transmittance data in reduced image format so one can see the difference with the Bladder data.

**Comment by waynewccheng** [comment]
Jocelyn: Regarding the yellows in the bladder image, if it's not an issue with the transmittance measurements, I found that one potential source of yellow spots in H&E staining could be the result of artifacts from tissue sample fixation (generally resulting in small yellow/brown spots).

**Comment by plemaillet** [comment]
Good point. 
I checked with the registered image from the Aperio and it does not show a yellow pixel at this location.
