### ISSUE TITLE
Unclear comment

### ISSUE THREAD

**Issue by waynewccheng** [plemaillet/read_spectral_data#3]
https://github.com/plemaillet/read_spectral_data/blob/4ef44f167fcb5f957c7adb979f4a46ed6d48713b/%40ReadSpectralDatabase/ReadSpectralDatabase.m#L165

Jocelyn: On line 165 of ReadSpectralDatabase.m, there's a comment that says "change to sig_s IT'S JUST SIZE". I was unsure about what this meant, but since the code itself calls for the 2nd dimension of sig_m, which is equal to the 2nd dim of sig_s, computation wise, nothing is actually affected (I'm just confused by the content of the comment itself).

WCC: We can remove it if it does not carry information.

**Comment by plemaillet** [comment]
Yes, it's a comment I put for myself and that I forgot to remove. I changed it to size(obj.sig_s, 2).
In the light of another comment by Jocelyn, do we want to keep all that's related to the computation of the covariance matrices in the code. 
Even though I have a sentimental inclinations to keep the error computations in the software due to my background, we are not using these for the end results,

**Comment by plemaillet** [comment]
Yes, it's a comment I put for myself and that I forgot to remove. I changed it to size(obj.sig_s, 2).
In the light of another comment by Jocelyn, do we want to keep all that's related to the computation of the covariance matrices in the code?
Even though I have a sentimental inclinations to keep the error computations in the software due to my background, we are not using these for the end results,
